// Date: 1/25/2015 4:27:42 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package dyrewulf.macabre.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBoneStack extends ModelBase
{
  //fields
    ModelRenderer Bar1;
    ModelRenderer Bell1a;
    ModelRenderer Bell1b;
    ModelRenderer Bell3a;
    ModelRenderer Bar3;
    ModelRenderer Bell3b;
    ModelRenderer Bell4a;
    ModelRenderer Bar4;
    ModelRenderer Bell4b;
    ModelRenderer Bell2a;
    ModelRenderer Bar2;
    ModelRenderer Bell2b;
    ModelRenderer Bell5a;
    ModelRenderer Bar5;
    ModelRenderer Bell5b;
    ModelRenderer Bell6a;
    ModelRenderer Bar6;
    ModelRenderer Bell6b;
    ModelRenderer Bell7a;
    ModelRenderer Bar7;
    ModelRenderer Bell7b;
    ModelRenderer Bell8a;
    ModelRenderer Bar8;
    ModelRenderer Bell8b;
  
  public ModelBoneStack()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Bar1 = new ModelRenderer(this, 12, 8);
      Bar1.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar1.setRotationPoint(2F, 8F, 5F);
      Bar1.setTextureSize(64, 32);
      Bar1.mirror = true;
      setRotation(Bar1, 0F, 1.570796F, 0F);
      Bell1a = new ModelRenderer(this, 0, 0);
      Bell1a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell1a.setRotationPoint(2F, 7F, -5F);
      Bell1a.setTextureSize(64, 32);
      Bell1a.mirror = true;
      setRotation(Bell1a, 0F, 1.570796F, 0F);
      Bell1b = new ModelRenderer(this, 6, 0);
      Bell1b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell1b.setRotationPoint(2F, 7F, 8F);
      Bell1b.setTextureSize(64, 32);
      Bell1b.mirror = true;
      setRotation(Bell1b, 0F, 1.570796F, 0F);
      Bell3a = new ModelRenderer(this, 0, 0);
      Bell3a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell3a.setRotationPoint(5F, 11F, -5F);
      Bell3a.setTextureSize(64, 32);
      Bell3a.mirror = true;
      setRotation(Bell3a, 0F, 0F, 0F);
      Bar3 = new ModelRenderer(this, 12, 8);
      Bar3.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar3.setRotationPoint(-5F, 12F, -5F);
      Bar3.setTextureSize(64, 32);
      Bar3.mirror = true;
      setRotation(Bar3, 0F, 0F, 0F);
      Bell3b = new ModelRenderer(this, 6, 0);
      Bell3b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell3b.setRotationPoint(-8F, 11F, -5F);
      Bell3b.setTextureSize(64, 32);
      Bell3b.mirror = true;
      setRotation(Bell3b, 0F, 0F, 0F);
      Bell4a = new ModelRenderer(this, 0, 0);
      Bell4a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell4a.setRotationPoint(5F, 11F, 2F);
      Bell4a.setTextureSize(64, 32);
      Bell4a.mirror = true;
      setRotation(Bell4a, 0F, 0F, 0F);
      Bar4 = new ModelRenderer(this, 12, 8);
      Bar4.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar4.setRotationPoint(-5F, 12F, 2F);
      Bar4.setTextureSize(64, 32);
      Bar4.mirror = true;
      setRotation(Bar4, 0F, 0F, 0F);
      Bell4b = new ModelRenderer(this, 6, 0);
      Bell4b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell4b.setRotationPoint(-8F, 11F, 2F);
      Bell4b.setTextureSize(64, 32);
      Bell4b.mirror = true;
      setRotation(Bell4b, 0F, 0F, 0F);
      Bell2a = new ModelRenderer(this, 0, 0);
      Bell2a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell2a.setRotationPoint(-5F, 7F, -5F);
      Bell2a.setTextureSize(64, 32);
      Bell2a.mirror = true;
      setRotation(Bell2a, 0F, 1.570796F, 0F);
      Bar2 = new ModelRenderer(this, 12, 8);
      Bar2.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar2.setRotationPoint(-5F, 8F, 5F);
      Bar2.setTextureSize(64, 32);
      Bar2.mirror = true;
      setRotation(Bar2, 0F, 1.570796F, 0F);
      Bell2b = new ModelRenderer(this, 6, 0);
      Bell2b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell2b.setRotationPoint(-5F, 7F, 8F);
      Bell2b.setTextureSize(64, 32);
      Bell2b.mirror = true;
      setRotation(Bell2b, 0F, 1.570796F, 0F);
      Bell5a = new ModelRenderer(this, 0, 0);
      Bell5a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell5a.setRotationPoint(5F, 19F, -5F);
      Bell5a.setTextureSize(64, 32);
      Bell5a.mirror = true;
      setRotation(Bell5a, 0F, 0F, 0F);
      Bar5 = new ModelRenderer(this, 12, 8);
      Bar5.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar5.setRotationPoint(-5F, 20F, -5F);
      Bar5.setTextureSize(64, 32);
      Bar5.mirror = true;
      setRotation(Bar5, 0F, 0F, 0F);
      Bell5b = new ModelRenderer(this, 6, 0);
      Bell5b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell5b.setRotationPoint(-8F, 19F, -5F);
      Bell5b.setTextureSize(64, 32);
      Bell5b.mirror = true;
      setRotation(Bell5b, 0F, 0F, 0F);
      Bell6a = new ModelRenderer(this, 0, 0);
      Bell6a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell6a.setRotationPoint(5F, 19F, 2F);
      Bell6a.setTextureSize(64, 32);
      Bell6a.mirror = true;
      setRotation(Bell6a, 0F, 0F, 0F);
      Bar6 = new ModelRenderer(this, 12, 8);
      Bar6.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar6.setRotationPoint(-5F, 20F, 2F);
      Bar6.setTextureSize(64, 32);
      Bar6.mirror = true;
      setRotation(Bar6, 0F, 0F, 0F);
      Bell6b = new ModelRenderer(this, 6, 0);
      Bell6b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell6b.setRotationPoint(-8F, 19F, 2F);
      Bell6b.setTextureSize(64, 32);
      Bell6b.mirror = true;
      setRotation(Bell6b, 0F, 0F, 0F);
      Bell7a = new ModelRenderer(this, 0, 0);
      Bell7a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell7a.setRotationPoint(-5F, 15F, -5F);
      Bell7a.setTextureSize(64, 32);
      Bell7a.mirror = true;
      setRotation(Bell7a, 0F, 1.570796F, 0F);
      Bar7 = new ModelRenderer(this, 12, 8);
      Bar7.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar7.setRotationPoint(-5F, 16F, 5F);
      Bar7.setTextureSize(64, 32);
      Bar7.mirror = true;
      setRotation(Bar7, 0F, 1.570796F, 0F);
      Bell7b = new ModelRenderer(this, 6, 0);
      Bell7b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell7b.setRotationPoint(-5F, 16F, 8F);
      Bell7b.setTextureSize(64, 32);
      Bell7b.mirror = true;
      setRotation(Bell7b, 0F, 1.570796F, 0F);
      Bell8a = new ModelRenderer(this, 0, 0);
      Bell8a.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell8a.setRotationPoint(2F, 15F, -5F);
      Bell8a.setTextureSize(64, 32);
      Bell8a.mirror = true;
      setRotation(Bell8a, 0F, 1.570796F, 0F);
      Bar8 = new ModelRenderer(this, 12, 8);
      Bar8.addBox(0F, 0F, 0F, 10, 3, 3);
      Bar8.setRotationPoint(2F, 16F, 5F);
      Bar8.setTextureSize(64, 32);
      Bar8.mirror = true;
      setRotation(Bar8, 0F, 1.570796F, 0F);
      Bell8b = new ModelRenderer(this, 6, 0);
      Bell8b.addBox(0F, 0F, 0F, 3, 5, 3);
      Bell8b.setRotationPoint(2F, 15F, 8F);
      Bell8b.setTextureSize(64, 32);
      Bell8b.mirror = true;
      setRotation(Bell8b, 0F, 1.570796F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bar1.render(f5);
    Bell1a.render(f5);
    Bell1b.render(f5);
    Bell3a.render(f5);
    Bar3.render(f5);
    Bell3b.render(f5);
    Bell4a.render(f5);
    Bar4.render(f5);
    Bell4b.render(f5);
    Bell2a.render(f5);
    Bar2.render(f5);
    Bell2b.render(f5);
    Bell5a.render(f5);
    Bar5.render(f5);
    Bell5b.render(f5);
    Bell6a.render(f5);
    Bar6.render(f5);
    Bell6b.render(f5);
    Bell7a.render(f5);
    Bar7.render(f5);
    Bell7b.render(f5);
    Bell8a.render(f5);
    Bar8.render(f5);
    Bell8b.render(f5);
  }
  
  public void renderModel(float f5)
  {
	  Bar1.render(f5);
	    Bell1a.render(f5);
	    Bell1b.render(f5);
	    Bell3a.render(f5);
	    Bar3.render(f5);
	    Bell3b.render(f5);
	    Bell4a.render(f5);
	    Bar4.render(f5);
	    Bell4b.render(f5);
	    Bell2a.render(f5);
	    Bar2.render(f5);
	    Bell2b.render(f5);
	    Bell5a.render(f5);
	    Bar5.render(f5);
	    Bell5b.render(f5);
	    Bell6a.render(f5);
	    Bar6.render(f5);
	    Bell6b.render(f5);
	    Bell7a.render(f5);
	    Bar7.render(f5);
	    Bell7b.render(f5);
	    Bell8a.render(f5);
	    Bar8.render(f5);
	    Bell8b.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
